name: CI -  Build & Push Strapi Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get_tag.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate image tag
        id: get_tag
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "image_tag=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE=balagouninaveen/strapi-app
          docker build -t $IMAGE:${{ steps.get_tag.outputs.image_tag }} .
          docker push $IMAGE:${{ steps.get_tag.outputs.image_tag }}
